
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch:
  platform: home_manager
sensor: !include sensor.yaml
utility_meter:
  car_mileage:
    source: sensor.mileage
    cycle: daily
  model3_car_daily_mileage:
    source: sensor.odometer
    cycle: daily
alert: !include alert.yaml
